const GET_DATAS = "GET_DATAS";
const GET_CATEGORIES = "GET_CATEGORIES";
const GET_EDIT_DATA = "GET_EDIT_DATA";
const GET_UPDATE_ERRORS = "GET_ERRORS";

export { GET_DATAS, GET_CATEGORIES, GET_EDIT_DATA, GET_UPDATE_ERRORS };
