import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import AppHeader from "../components/AppHeader";
import AppBar from "../components/AppBar";
import AppManuBar from "../components/AppManuBar";
import AppBarContext from "./context/AppBarContext";
import AppFooterManuBar from "../components/AppFooterManuBar";
import Message from "../components/Message";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppHeader />
          <div className="sticky top-0">
            <AppBar />
            <AppManuBar />
          </div>
          {children}
          <Message />
          <AppFooterManuBar />
        </Providers>
      </body>
    </html>
  );
}
